### ISSUE TITLE
Expe 2 TODO

### ISSUE THREAD

**Issue by DominiqueMakowski** [RealityBending/InteroceptionScale#2]
For when you're back from the break @AnafNeves @EmmaLBenn @maisiebennett 

- [x] Add all questionnaires as separate entities (not as different pages in the same jspysch survey but as different surveys)
- [x] Add questions related to somatic disorders (in pathologgy.js)
- [x] Add question about weight & height in demographics (to compute BMI)
- [x] Add at the end a "general" radar chart - not based on only the MINT, but could have the following dimensions: "Body connection" (mean of IAS), "Coping skills" (ERQ - reappraisal mean), "Emotion expression" (mean affect intensity), "Low mood" (mean PHQ4)
  - [x] we could add a screenshot as an example in the  instructions at the beginning to motivate people to do the whole thing seriously 
- [x] I'll deal with the randomizing then once we have all elements working

**Comment by DominiqueMakowski** [comment]
(`study2/experiment` now supersedes `study2/experiment_ana`)

**Comment by DominiqueMakowski** [comment]
*kind bump*

**Comment by DominiqueMakowski** [comment]
TODOS

- [x] Rename attention checks items as e.g., `*_AttentionCheck_1` instead of `_A` (slightly more explicit and must be consistent with the naming in each scale)
- [x] BPQ: replace with BPQ-VSF (short form 12 items): https://journals.plos.org/mentalhealth/article?id=10.1371/journal.pmen.0000038
- Revise emotion regulation: reading [this](http://dx.doi.org/10.1016/j.paid.2016.06.045) made me wonder what was the best alternative to measure ER. Popular questionnaires include ERQ, DERS, CERQ. I am tempted to:
  - [x] Remove ERQ
  - [x] Add CERQ https://journals.sagepub.com/doi/pdf/10.1177/14034948231225616
  - [x] Add Brief ERS (https://link.springer.com/article/10.1007/s12144-023-05323-4)
- [x] Add questions about wearables
- [x] Add questions about physical activity (can be grouped with the above on two separate pages from the same survey)
- [ ] Start preprocessing script

**Comment by DominiqueMakowski** [comment]
@EmmaLBenn @maisiebennett lmk if you need help or precision

**Comment by DominiqueMakowski** [comment]
- [x] Keep only one attention check for the MINT 
- [x] Add a screenshot as an example in the instructions at the beginning to motivate people to do the whole thing seriously

**Comment by DominiqueMakowski** [comment]
Once the above is done, we should be pretty much ready, could you:

1. Reactivate the data saving code (I have created a study2 folder inside the same InteroceptionScale box folder to put the data)
2. Pilot it all once again, make sure it flows well and that the randomization worked as expected and that nothing is missing
3. Let me know once we made sure it all worked, I will send it to Giulia for a final check 
4. Meanwhile, make sure the data is saved and *check* that it got saved with a preprocessing script draft

**Comment by DominiqueMakowski** [comment]
Could you also make a graph (in powerpoint) showing the procedure (with boxes and like all the different phases and questionnaires etc)

**Comment by DominiqueMakowski** [comment]
**Education level**
- [ ] Could add UK options/equivalents?  
- [x] Could drop additional info about education (discipline) unless you feel very relevant?

**MINT**
- [x] “I always feel in my body if I am sexually aroused” – there is something that jarred about this wording – I think it needs an ‘IT’ “If I am sexually aroused, I always feel it in my body” or “I always feel it in my body if I am sexually aroused”
- [x] “to the left of this question” à the “very left” or “extreme left”? (you want them to select 0 rather than 1)?

**TAS**
- [ ] For analysis consider calculating the score without the very interoceptive item: “I am often puzzled by sensations in my body”

**Other**
- [x] think of something nice instead of what has happened – needs a capital ‘T’ (I know this is picky but everything else is so perfect!!)
- [x] Active workout question – the category options seem somewhat arbitrary (big difference between 2 and 6 hours to me). Why not just ask people to specify in hours and mins and then you can put in bins later if you like?
  - **Edit and send me a screenshot of how the new version looks like** 
 
**Device:**
- [x] I think there is a difference between owning and using a device (e.g., I own but no longer use). So perhaps “do you use…”?
- [x] Options for checking seemed to miss what I think might be the most common option(s) “every day” so suggest adding “every day” or “once a day” and “several times a day”

**Debrief**
- [x] Wording “hence why we are doing this research”
- [x] This was the only page where the continue button was in a different place and you also had to click on it to see the debrief information (suggest moving to bottom right if poss and also instructing ppts to click that button to move forward)
- [x] Still getting this page after writing this email (see screenshot below) – maybe because not set up properly yet but thought I would mention otherwise I imagine you’ll get lots of emails from ppts about their responses not being submitted!
